# Generated by Django 4.2.2 on 2023-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default="Price is not available at the moment",
                        max_digits=10,
                    ),
                ),
                ("certificate", models.ImageField(null=True, upload_to="certificates")),
            ],
        ),
    ]
