# Generated by Django 4.2.2 on 2023-06-23 09:38

import amazon.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amazon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="certificate",
            field=models.ImageField(
                null=True, upload_to=amazon.models.upload_certificate
            ),
        ),
    ]
